/**
 * Check every curated model against Hugging Face and list popular models we don't cover yet.
 *
 *   npm run refresh:models            (token from HF_TOKEN or ~/.config/huggingface/token)
 *
 * Writes research/model-refresh-YYYY-MM-DD.md. It never edits data/models.ts —
 * curated entries are reviewed by hand.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import path from "node:path";
import { MODELS } from "../data/models";
import { parseHfModel, type HfConfig, type HfModelInfo } from "../lib/hf/parse";
import { kvBytesPerToken } from "../lib/memory";

const tokenFile = path.join(homedir(), ".config/huggingface/token");
const token = process.env.HF_TOKEN ?? (existsSync(tokenFile) ? readFileSync(tokenFile, "utf8").trim() : undefined);
const H: HeadersInit = token ? { Authorization: `Bearer ${token}` } : {};
const HUB = "https://huggingface.co";
const today = new Date().toISOString().slice(0, 10);

async function json<T>(url: string): Promise<T | null> {
  const r = await fetch(url, { headers: H });
  return r.ok ? ((await r.json()) as T) : null;
}

const repoOf = (url: string) => url.match(/huggingface\.co\/([^/]+\/[^/?#]+)/)?.[1];
const pct = (a: number, b: number) => Math.abs(a - b) / Math.max(1e-9, Math.abs(b));

const rows: string[] = [];
const issues: string[] = [];
for (const m of MODELS) {
  const repo = repoOf(m.source.url);
  if (!repo) {
    rows.push(`| ${m.name} | — | no Hugging Face source | |`);
    continue;
  }
  const info = await json<HfModelInfo>(`${HUB}/api/models/${repo}?expand[]=safetensors&expand[]=cardData&expand[]=config&expand[]=pipeline_tag&expand[]=downloads&expand[]=gated`);
  const config = await json<HfConfig>(`${HUB}/${repo}/resolve/main/config.json`);
  if (!info || !config) {
    rows.push(`| ${m.name} | ${repo} | ⚠ couldn't read (gated or moved) | |`);
    issues.push(`${m.name}: couldn't read ${repo}`);
    continue;
  }
  try {
    const { model: hub } = parseHfModel({ repo, info, config, today });
    const diffs: string[] = [];
    if (pct(hub.parameterCount, m.parameterCount) > 0.03) diffs.push(`params ${m.parameterCount}B → ${hub.parameterCount}B`);
    if (pct(kvBytesPerToken(hub), kvBytesPerToken(m)) > 0.1 && !m.architecture.kvBytesPerTokenOverride) diffs.push(`KV ${Math.round(kvBytesPerToken(m) / 1024)}→${Math.round(kvBytesPerToken(hub) / 1024)} KB/token`);
    if (hub.vision !== m.vision) diffs.push(`vision ${m.vision}→${hub.vision}`);
    if (hub.contextWindow !== m.contextWindow && hub.contextWindow > m.contextWindow) diffs.push(`config context ${hub.contextWindow} (catalog ${m.contextWindow})`);
    rows.push(`| ${m.name} | ${repo} | ${diffs.length ? "⚠ " + diffs.join("; ") : "✓ matches"} | ${info.downloads?.toLocaleString("en-US") ?? ""} |`);
    if (diffs.length) issues.push(`${m.name}: ${diffs.join("; ")}`);
  } catch (e) {
    rows.push(`| ${m.name} | ${repo} | ⚠ parse error: ${(e as Error).message} | |`);
  }
}

// Popular models not yet in the catalog
const known = new Set(MODELS.map((m) => repoOf(m.source.url)?.toLowerCase().split("/")[1]));
const trending = (await json<{ id: string; downloads?: number; likes?: number }[]>(`${HUB}/api/models?filter=text-generation&sort=trendingScore&direction=-1&limit=60`)) ?? [];
const fresh = trending
  .filter((t) => !known.has(t.id.split("/")[1].toLowerCase()))
  // Skip quantized re-uploads and uncensored/merged fine-tunes; keep well-adopted releases.
  .filter((t) => !/gguf|mlx|awq|gptq|fp8|bnb|exl|-4bit|-8bit|abliterat|obliterat|uncensor|heretic|merge/i.test(t.id) && (t.downloads ?? 0) >= 25_000)
  .sort((a, b) => (b.downloads ?? 0) - (a.downloads ?? 0))
  .slice(0, 15);

const report = `# Model catalog refresh — ${today}

Compared ${MODELS.length} curated models with their Hugging Face config.json. ${issues.length} need a look.

| Model | Repo | Result | Downloads |
|---|---|---|---|
${rows.join("\n")}

## Trending text-generation models not in the catalog

${fresh.map((t) => `- [${t.id}](https://huggingface.co/${t.id}) — ${t.downloads?.toLocaleString("en-US") ?? "?"} downloads, ${t.likes ?? 0} likes`).join("\n")}

_Generated by scripts/refresh-models.mts. Review before editing data/models.ts._
`;
const out = path.join("research", `model-refresh-${today}.md`);
writeFileSync(out, report);
console.log(`${issues.length} issue(s). Report: ${out}`);
for (const i of issues) console.log(" -", i);
